#!/usr/bin/env python3

# Artur Asimov
# https://github.com/artur-asimov/tinyfetch

from typing import Text
import psutil
import distro
import os
import platform
import cpuinfo
import socket
import configparser
import os.path

from colorama import Fore
from datetime import datetime

ascii = (
    '    .--.    ',
    '   |o_o |   ',
    '   |:_/ |   ',
    '  //   \\ \\  ',
    ' (|     | ) ',
    '/\'\_   _\/`\\',
    '\___)=(___/ '
)

if os.path.isfile(f'/home/{os.getlogin()}/.config/tinyfetch/config.ini') :
    config = configparser.ConfigParser()
    config.read(f'/home/{os.getlogin()}/.config/tinyfetch/config.ini')
else :
    print('Cannot detect your configuration file in [~/.config/tinyfetch/config.ini]. Run install script again.')

def get_size(bytes, suffix="B"):
    factor = 1024
    for unit in ["", "K", "M", "G", "T", "P"]:
        if bytes < factor:
            return f"{bytes:.2f}{unit}{suffix}"
        bytes /= factor

boot_time_timestamp = psutil.boot_time()
bt = datetime.fromtimestamp(boot_time_timestamp)

uname = platform.uname()
svem = psutil.virtual_memory()


# Storing configuration settings in some variables
try:
    TitleColor = getattr(Fore, config['THEME']['titles_color'])
    TextColor = getattr(Fore, config['THEME']['text_color'])
    ArtColor = getattr(Fore, config['THEME']['art_color'])

    output = f"""{TextColor}\t\t {"-"*4}{TitleColor}{os.getlogin()}{TextColor}@{TitleColor}{platform.node()}{TextColor}{"-"*4}
    {ArtColor}{ascii[0]} {TitleColor}System:{TextColor} {uname.system} {uname.machine}
    {ArtColor}{ascii[1]} {TitleColor}Distro:{TextColor} {distro.id()}
    {ArtColor}{ascii[2]} {TitleColor}Kernel:{TextColor} {uname.release}
    {ArtColor}{ascii[3]} {TitleColor}Boot Time:{TextColor} {bt.year}/{bt.month}/{bt.day} {bt.hour}:{bt.minute}:{bt.second}
    {ArtColor}{ascii[4]} {TitleColor}Processor:{TextColor} {cpuinfo.get_cpu_info()["brand_raw"]}
    {ArtColor}{ascii[5]} {TitleColor}Memory:{TextColor} {get_size(svem.used)} / {get_size(svem.total)}
    {ArtColor}{ascii[6]} {TitleColor}IP Address:{TextColor} {socket.gethostbyname(socket.gethostname())}"""

    print(output)
except:
    print('tinyfetch error! Check your configuration file.')


